### ISSUE TITLE
Unity 5.6.5 Android iL2cpp build crash on application.Quit() was called.

### ISSUE THREAD

**Issue by jingjieyeh** [BranchMetrics/unity-branch-deep-linking-attribution#124] opened 2018-03-20 03:12 UTC
This issue is occurred to be upgrading my Unity 5.5.2 project to Unity 5.6.5 , Unity 2017.1 or Unity 2017.3 version.  I have **used Application.Quit() to close Unityandroid iL2Cpp Build** application. 
After We waited for 3-5 seconds the app was crashed to show "Unfortunately (app) has stopped working" message box.

I have tested to upgrading Branch.io Unity Plug-in version from 0.3.x (Branch-2.5.9_core) to Latest version of  v0.4.6, the crash issue is still existed.

But fortunately if the app is **Android Mono build** or **Removing Branch.io Unity Plug-in, this issue will not happen**.

if Branch.io supported team can help me to fixed this issue,  I am very appreciated it.

Thanks.

**Comment by antonargunov** [comment] 2018-03-20 07:15
@jingjieyeh thanks for report, let me check.

**Comment by jingjieyeh** [comment] 2018-03-21 05:36
@antonargunov  
Thanks for your assistance and reply. 
Branch.io is really a great service for our project.  
If this issue can be solved, I believe that the stability and experience of this plugin will be better for Unity users.

I am also very much looking forward to being able to get the updated package to fix this issue.

**Comment by antonargunov** [comment] 2018-03-22 07:40
@jingjieyeh unfortunately I can't reproduce this issue in out testbed:
- Unity 5.6.5f1
- gradle/internal + ill2cpp
- samsung galaxy s8 + Android 7.0

This is a link for testbed.apk, try to launch on your device:
https://www.dropbox.com/s/nc8f1q616nesny9/testbed.apk?dl=0

Also, may be you can export project and run your project under AndroidStudio to create a log?
It's very interesting to see what happens after calling Application.Quit().

**Comment by csalmi-branch** [comment] 2019-01-17 00:36
@jingjieyeh are you still experiencing this issue? Is so, could you please provide any logs you might have available?

**Comment by nkls2000** [comment] 2019-03-28 19:37
Not sure if its related, but we are experiencing this: 

f we quit the game from the native android back button (using Application.Quit), we get this error:

Activity io.branch.unity.BranchUnityActivity has leaked IntentReceiver com.unity.purchasing.googleplay.GooglePlayPurchasing$5@398122e that was originally registered here. Are you missing a call to unregisterReceiver()?

Anyone has an idea on how to solve that error? It causes big troubles next time we start the app and try to initialize the Unity IAP.

Here is our log:

2019-03-28 16:49:05.338 3652-3891/? I/WindowManager_SurfaceController: Destroying surface Surface(name=com.majorfrank.lifty/io.branch.unity.BranchUnityActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2906 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1120 com.android.server.wm.WindowState.removeLocked:1880 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2924 com.android.server.wm.WindowManagerService.removeWindowLocked:2874 com.android.server.wm.WindowManagerService.removeWindowLocked:2689 com.android.server.wm.WindowManagerService.removeWindow:2684 com.android.server.wm.Session.remove:218

2019-03-28 16:49:05.338 3092-3304/? I/SurfaceFlinger: id=118 Removed CranchUnity (3/5)

2019-03-28 16:49:05.338 3092-25096/? I/SurfaceFlinger: id=118 Removed CranchUnity (-2/5)

2019-03-28 16:49:05.343 17105-17105/? E/ActivityThread: Activity io.branch.unity.BranchUnityActivity has leaked IntentReceiver com.unity.purchasing.googleplay.GooglePlayPurchasing$5@398122e that was originally registered here. Are you missing a call to unregisterReceiver()?

android.app.IntentReceiverLeaked: Activity io.branch.unity.BranchUnityActivity has leaked IntentReceiver com.unity.purchasing.googleplay.GooglePlayPurchasing$5@398122e that was originally registered here. Are you missing a call to unregisterReceiver()?

at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1222)

at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:993)

at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1331)

at android.app.ContextImpl.registerReceiver(ContextImpl.java:1311)

at android.app.ContextImpl.registerReceiver(ContextImpl.java:1305)

at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:617)

at com.unity.purchasing.googleplay.GooglePlayPurchasing.registerPurchasesUpdatedReceiver(GooglePlayPurchasing.java:547)

at com.unity.purchasing.googleplay.GooglePlayPurchasing.<init>(GooglePlayPurchasing.java:124)

at com.unity.purchasing.googleplay.GooglePlayPurchasing.instance(GooglePlayPurchasing.java:80)

at com.unity3d.player.UnityPlayer.nativeRender(Native Method)

at com.unity3d.player.UnityPlayer.c(Unknown Source)

at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)

at android.os.MessageQueue.next(MessageQueue.java:392)

at android.os.Looper.loop(Looper.java:136)

at com.unity3d.player.UnityPlayer$e.run(Unknown Source)

2019-03-28 16:49:05.344 17105-17105/? E/ActivityThread: Activity io.branch.unity.BranchUnityActivity has leaked ServiceConnection com.unity.purchasing.googleplay.BillingServiceManager$1@4df5f45 that was originally bound here

android.app.ServiceConnectionLeaked: Activity io.branch.unity.BranchUnityActivity has leaked ServiceConnection com.unity.purchasing.googleplay.BillingServiceManager$1@4df5f45 that was originally bound here

at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1399)

at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1294)

at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1503)

at android.app.ContextImpl.bindService(ContextImpl.java:1475)

at android.content.ContextWrapper.bindService(ContextWrapper.java:688)

at com.unity.purchasing.googleplay.BillingServiceManager.bindToGooglePlayService(BillingServiceManager.java:114)

at com.unity.purchasing.googleplay.BillingServiceManager$2.run(BillingServiceManager.java:149)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)

at java.lang.Thread.run(Thread.java:762)

2019-03-28 16:49:05.345 17105-17105/? E/ActivityThread: Activity io.branch.unity.BranchUnityActivity has leaked ServiceConnection null that was originally bound here

android.app.ServiceConnectionLeaked: Activity io.branch.unity.BranchUnityActivity has leaked ServiceConnection null that was originally bound here

at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1399)

at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1294)

at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1503)

at android.app.ContextImpl.bindService(ContextImpl.java:1475)

at android.content.ContextWrapper.bindService(ContextWrapper.java:688)

at com.unity3d.player.UnityPlayer.nativeRender(Native Method)

at com.unity3d.player.UnityPlayer.c(Unknown Source)

at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)

at android.os.MessageQueue.next(MessageQueue.java:392)

at android.os.Looper.loop(Looper.java:136)

at com.unity3d.player.UnityPlayer$e.run(Unknown Source)

**Comment by antonargunov** [comment] 2019-03-28 20:03
@nkls2000 as I can see this is unsolved Unity3d issue:
https://forum.unity.com/threads/unity-2018-1-0f2-unity-iap-error-when-android-app-force-closing.531778/

**Comment by csalmi-branch** [comment] 2019-05-01 17:44
Due to the age and inactivity of the original reported issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!

**Closed as completed by csalmi-branch** 2019-05-01 17:44 UTC
