### ISSUE TITLE
Deepview redirects to default / desktop location instead of app on new iPadOS Beta

### ISSUE THREAD

**Issue by NumaNumaNuma** [BranchMetrics/unity-branch-deep-linking-attribution#157] opened 2019-09-06 01:43 UTC
Clicking a branch link doesn't take you to the iOS app if the device is running iPadOS, it just takes you to the fallback location (desktop in our case). It works fine on all iOS 13 versions.

Am I missing something or is iPadOS not supported yet?

Thanks

**Comment by NumaNumaNuma** [comment] 2019-09-06 02:59
updating to new iOS beta seems to have fixed it

**Comment by NumaNumaNuma** [comment] 2020-04-23 00:01
Hi, it looks like this is still happening on an iPad running iPadOS.
If the url scheme / universal link works, you're taken to the app, all good.
If you're taken to a deepview, you will be redirected to the desktop url.

Is iPadOS treated as a desktop platform and not standard iOS?
Thanks

**Comment by echo-branch** [comment] 2020-04-23 17:11
Could you open a new ticket for this?  I'll open an internal ticket to check on this.  iPadOS should not be treated as a desktop, however it self reports as a desktop so there could be an issue server side determining what device type it is.

Also are you able to provide OS version, browser version and possibly a sample link?

**Comment by NumaNumaNuma** [comment] 2020-05-04 04:03
Sorry for the delay.
OS is IpadOS 13.1.1
Browser is Safari, not sure how to get the version number on an iPad.

I have a link ready, is there a way I can send it to you privately?

**Comment by echo-branch** [comment] 2020-05-06 20:33
@NumaNumaNuma 
Thanks for the info.  You can send the link to echo@branch.io
I'm hoping to devote time to this early in the next sprint.

**Comment by NumaNumaNuma** [comment] 2020-05-08 01:48
Great, I sent you an email with the link 👍

**Comment by NumaNumaNuma** [comment] 2020-05-18 03:02
Hi @echo-branch,
Just checking in. Have you been able to reproduce / confirm the problem? Or is it something I'm doing wrong?
I'd love to know if I should keep digging or just wait for a fix :)
Thanks

**Comment by PreludeAndFugue** [comment] 2020-06-03 16:36
I have the same problem on an iPad with iPadOS 13.4.1.

When I tap a branch link it redirects to the "text-me-the-app page", which is the default redirect for the Desktop.

**Comment by echo-branch** [comment] 2020-06-03 16:44
@PreludeAndFugue 

Just to update here.  There's an issue with us misidentifying iOS 13 iPads that have the "request desktop site" setting in Safari changed.  There's a ticket to fix this in the current sprint, though it's taking longer than expected.

You may be able to work around it by defaulting to the iPad version of the site on failure to identify, but that might not work if you have a desktop site too.

**Comment by NumaNumaNuma** [comment] 2020-07-23 11:15
Hi @echo-branch, any news? 😁

**Comment by rupam-ghosh** [comment] 2020-09-18 07:27
@echo-branch Please update on your progress in this issue, Even I am facing the same issue.

**Comment by rupam-ghosh** [comment] 2020-09-18 07:29
@NumaNumaNuma why have you closed this issue? Is it resolved for you ?

**Comment by NumaNumaNuma** [comment] 2020-09-18 07:56
I closed it in 2019 when I thought it worked, turns out it was still broken. I'll re-open!

**Comment by rupam-ghosh** [comment] 2020-09-18 08:06
@echo-branch please confirm when this issue will be picked up by your team.

**Comment by NumaNumaNuma** [comment] 2021-03-01 22:36
@echo-branch any news on this? 😅

**Comment by echo-branch** [comment] 2021-03-01 22:51
Hey sorry for not responding earlier, I missed the ping since you reopened the issue.  The original backend ticket is marked fixed, but I'll follow up with team.

**Comment by echo-branch** [comment] 2021-03-02 21:12
I reopened a ticket for the backend team.

**Comment by NumaNumaNuma** [comment] 2021-05-05 08:56
@echo-branch Friendly check-in. Any updates?

**Comment by echo-branch** [comment] 2021-05-05 17:11
Hey. So we confirmed that the original fix wasn't completed properly. The server team has been completely devoted to iOS 14.5 work, so they haven't gotten it yet. I am hoping it makes it into the next sprint now that iOS 14.5 is out.

**Comment by mnifakram** [comment] 2021-06-28 22:46
Any updates on this? Is it on the map?

**Comment by klim-branch** [comment] 2022-03-08 13:46
Hey team!

Apparently, this IPadOS issue was affecting the entire Branch SDK, since Apple announced that IPad is now a desktop from IOS 13 ( IPadOS 13)
Now on our Branch Dashboard, you can set up the IpadOS deep linking there. 

Please have a look at the attached image :)
[https://flic.kr/p/2n7qFMS](https://flic.kr/p/2n7qFMS)

**Closed as completed** 2023-01-05 08:05 UTC
